instagram/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name="accounts"
urlpatterns = [
   path("register/",views.RegisterView.as_view(),name="register"),
   path("register/<str:user_id>/<str:token>/",views.ActivateLink.as_view(),name="register_done"),
   path("password_setform",views.PasswordSetView.as_view(),name="password_setform"),
   path("login/",views.LoginView.as_view(),name="login"),
   path("logout/",views.LogoutView.as_view(),name="logout"),
   path("password_reset/",views.PasswordResetView.as_view(),name="password_reset"),
   path("reset/<str:uidb64>/<str:token>/",auth_views.PasswordResetConfirmView.as_view(template_name="accounts/authorization/passwordResetConfirm.html"),name="password_reset_confirm"),
   path("reset/done/",auth_views.PasswordResetCompleteView.as_view(template_name="accounts/authorization/passwordResetComplete.html"),name="password_reset_complete"),
   path("password_reset_done/",views.PasswordResetDoneView.as_view(),name="password_reset_done"),
   path("password_change/",views.PasswordChangeView.as_view(),name="password_change"),
]

instagram/api/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from api import views

app_name="api"

urlpatterns = [
  path("add_like/",views.CreateLikeView.as_view(),name="add_like"),
  path("image/<int:profile_id>/<int:post_id>/",views.ImageView.as_view(),name="image_view"),
  path("subscribe/",views.CreateSubscribeView.as_view(),name="add_subscriber"),
  path("comment/",views.CreateCommentView.as_view(),name="add_comment"),
  path("delete_subscribe/<profile_id>/<user_id>/",views.DeleteSubscribeView.as_view(),name="delete_subscriber"),
  path("delete_like/<post_id>/<user_id>/",csrf_exempt(views.DeleteLikeView.as_view()),name="delete_like")
]

instagram/chat/urls.py
from django.urls import path
from chat import views

app_name="chat"
urlpatterns = [
    path("inbox/",views.inbox,name="inbox"),
    path("chat/<str:label>/",views.chat,name="chat"),
    path("chat_create/<str:username>/",views.chat_create,name="chat_create")
]

instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("instagram_profile.urls",namespace="instagram_profile")),
    path("",include("accounts.urls",namespace="account")),
    path("",include("chat.urls",namespace="chat")),
    path("api/",include("api.urls",namespace="api"))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

instagram/instagram_profile/urls.py
from django.urls import path
from instagram_profile import views
# from instagram_profile.views import ProfileView


app_name="instagram_profile"
urlpatterns = [
   path("",views.index,name="index"),
   path("friends/",views.ProfileListView.as_view(),name="profile_list"),
   path("feed/",views.FeedView.as_view(),name="feed"),
   path("profile/<int:pk>/",views.ProfileView.as_view(),name="profile"),
   path("profile/update_profile/<int:pk>/",views.UpdateProfileView.as_view(),name="update_profile"),
   path("profile/subscribers/<str:username>/",views.SubscribersView.as_view(),name="subscribers_list"),
   path("profile/followers/<str:username>/",views.FollowersView.as_view(),name="followers_list"),
   path("post/<int:profile_id>/<int:post_id>/",views.PostView.as_view(),name="post"),
   path("post/add_post",views.AddPostView.as_view(),name="add_post"),
]

instagram/instagram_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from datetime import datetime
from django.urls import reverse

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    followers = models.ManyToManyField('Profile',related_name='profile_followers',blank=True)
    subscribers = models.ManyToManyField('Profile',related_name='profile_subscribers',blank=True)
    image_pic = ProcessedImageField(upload_to="photos",default="default.jpg",format='JPEG',options={'quality':100},null=True,blank=True)
    bio = models.CharField(max_length=200)
    created_at = models.DateTimeField(default=datetime.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=["created_at"]

    def get_count_of_post(self):
        return self.post_set.count()

    def get_count_of_subscribers(self):
        return self.subscribers.count()

    def get_count_of_followers(self):
        return self.followers.count()

    def __str__(self):
        return self.user.username



class Post(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now)
    text = models.CharField(max_length=200)
    first_image = ProcessedImageField(upload_to="first_image",format="JPEG",options={'quality':100},null=True,blank=True)

    def get_absolute_url(self):
        return reverse('post',args=[str(self.profile.id),str(self.id)])

    def get_count_of_likes(self):
        return self.like_set.count()

    def get_count_of_comments(self):
        return self.comment_set.count()

    def __str__(self):
        return "Post id:"+str(self.id)+" "+str(self.profile.user.username)


class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)

    class Meta:
        unique_together = ("post","user")

    def __str__(self):
        return "Id: "+str(self.id) + " Username:"+self.user.username+" Post:"+str(self.post.id)


class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    created_at = models.DateTimeField(default=datetime.now)

    def __str__(self):
            return "Id: "+str(self.id) + " Username:"+self.user.username+" Post:"+str(self.post.id)


class Image(models.Model):
    image_url = ProcessedImageField(upload_to="post",processors=[ResizeToFill(200,200)],format='JPEG',options={'quality':100},blank=True,null=True)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

instagram/instagram_profile/forms.py
from django import forms
from django.contrib.auth.models import User
from instagram_profile.models import Profile, Comment


class AddPostForm(forms.Form):
    text = forms.CharField(required=False)
    first_image = forms.ImageField()
    attachments = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple':True}),required=False)


class UpdateProfileForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super(UpdateProfileForm,self).__init__(*args,**kwargs)
        self.fields['bio'].required=False

    class Meta:
        model = Profile
        fields = ('image_pic','bio',)


class UsernameForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username',)

instagram/instagram_profile/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from instagram_profile.models import Profile,Image,Post, Comment, Like
from instagram_profile.forms import AddPostForm,UpdateProfileForm,UsernameForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
#for ajax,api
#HttpResponses,reverse
from django.http import HttpResponse
from django.urls import reverse
from django.http import HttpResponseRedirect
#Views
from django.views import View
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("instagram_profile:feed"))
    else:
        return HttpResponseRedirect(reverse("accounts:login"))


class UpdateProfileView(LoginRequiredMixin,UpdateView):
    model = Profile
    second_model = User
    form_class = UpdateProfileForm
    second_form_class = UsernameForm
    pk_url_kwarg = 'pk'
    template_name = "instagram_profile/profile/update_profile.html"

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return HttpResponseRedirect(reverse("instagram_profile:profile",args=(pk,)))

    def get_context_data(self,**kwargs):
        context = super(UpdateProfileView,self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        profile = get_object_or_404(self.model,id=int(pk))
        user = get_object_or_404(self.second_model,id=int(pk))
        context['profile_form'] = self.form_class(instance=profile)
        context['username_form'] = self.second_form_class(instance=user)
        return context

    def form_invalid(self,profile_form,username_form,*args,**kwargs):
        return self.render_to_response(self.get_context_data({'profile_form':profile_form,'username_form':username_form}))

    def post(self,request,*args,**kwargs):
        pk = self.kwargs.get('pk')
        profile = get_object_or_404(self.model,id=int(pk))
        user = get_object_or_404(self.second_model,id=int(pk))
        profile_form = self.form_class(instance=profile,data=request.POST,files=request.FILES)
        username_form = self.second_form_class(instance=user,data=request.POST)
        if profile_form.is_valid() and username_form.is_valid():
            profile_form.save()
            username_form.save()
            return self.get_success_url()
        else:
            return self.form_invalid(profile_form,username_form)


class AddPostView(View,LoginRequiredMixin):
    template_name = "instagram_profile/post/add_post.html"
    form_class = AddPostForm

    def get(self,request,*args,**kwargs):
        form = self.form_class()
        context = {"form":form}
        return render(request,self.template_name,context=context)

    def post(self,request,*args,**kwargs):
        profile = self.request.user.profile
        form = self.form_class(data=request.POST,files=request.FILES)
        if form.is_valid():
            text = form.cleaned_data["text"]
            first_image = form.cleaned_data["first_image"]
            attachments = self.request.FILES.getlist("attachments")
            post = Post(profile=profile,text=text,first_image=first_image)
            post.save()
            for im in attachments:
                Image.objects.create(post_id=post.id,image_url=im)
            return HttpResponseRedirect(reverse('instagram_profile:post',args=(profile.id,post.id)))


class PostView(DetailView):
    model = Post
    template_name = "instagram_profile/post/post.html"
    context_object_name = "post"

    def get_object(self,**kwargs):
        post_id = self.kwargs.get('post_id')
        return Post.objects.get(id=post_id)

    def get_context_data(self,**kwargs):
        context = super(PostView,self).get_context_data(**kwargs)
        post_id = self.kwargs.get('post_id')
        profile_id = self.kwargs.get('profile_id')
        comments = Comment.objects.filter(post__id=post_id,post__profile__id=profile_id)
        liked = False
        if Like.objects.filter(user=self.request.user.id,post__id=post_id).exists():
            liked = True
        context["is_liked"] = liked
        context["comments"] = comments
        return context


class ProfileView(View,LoginRequiredMixin):
    template_name = "instagram_profile/profile/profile.html"

    def get(self,request,*args,**kwargs):
        pk = self.kwargs.get('pk')
        profile = Profile.objects.get(id=pk)
        follower = request.user.profile
        post = Post.objects.filter(profile__id=pk)
        is_subscribed = True if follower in profile.subscribers.all() else False
        context = {"profile":profile,"post":post,"is_subscribed":is_subscribed}
        return render(request,self.template_name,context=context)


class SubscribersView(View,LoginRequiredMixin):
    template_name = "instagram_profile/subscribers/subscribers_list.html"

    def get(self,request,username):
        profile = Profile.objects.get(user=User.objects.get(username=username))
        subscribers = profile.subscribers.all()
        context={"subscribers":subscribers}
        return render(request,self.template_name,context=context)


class FollowersView(View,LoginRequiredMixin):
    template_name = "instagram_profile/followers/followers_list.html"

    def get(self,request,username):
        profile = Profile.objects.get(user=User.objects.get(username=username))
        followers = profile.followers.all()
        context = {"followers":followers}
        return render(request,self.template_name,context=context)


class ProfileListView(ListView,LoginRequiredMixin):
    model = Profile
    template_name = "instagram_profile/profile/profile_list.html"
    context_object_name = 'profile_to_list'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        return context


class FeedView(View,LoginRequiredMixin):
    template_name = "instagram_profile/feed/feed.html"

    def get(self,request):
        profile = Profile.objects.get(user=request.user.id)
        subscribers = profile.followers.all()
        posts = Post.objects.filter(profile__in=subscribers).order_by("created_at")
        context = {"posts":posts}
        return render(request,self.template_name,context=context)

instagram/templates/instagram_profile/profile/profile.html
{%extends "base.html"%}
{% block content %}
<h1>Profile</h1>
{%if user.is_authenticated%}
   {%if user.id == profile.id %}
   <a href="{% url 'instagram_profile:add_post' %}">Add post</a>
   <a href="{%url 'instagram_profile:update_profile' profile.id%}">Update profile</a>
   <a href="{% url 'accounts:password_change' %}">Password Change Form</a>
   {%else%}
   <a href="{% url 'chat:chat_create' profile.user.username %}">Send message</a><br><br>
   <form id="subscribe-form" method="POST">
     {% if is_subscribed %}
     <button type="submit" value="{{profile.id}}" class="unsubscribe" name="profile-id" id="profile-id">Unsubscribe</button>
     {%else%}
     <button type="submit" value="{{profile.id}}" class="subscribe" name="profile-id" id="profile-id">Subscribe</button>
     {%endif%}
   </form>
   {%endif%}
{%endif%}
<h2>{{profile.user.username}}</h2>
<p><strong>Posts:</strong>{{profile.get_count_of_post}}</p>
<p><a href="{% url 'instagram_profile:subscribers_list' profile.user.username %}">Subscribers</a>:<strong id="count-subscribers">{{profile.get_count_of_subscribers}}</strong></p>
<p><a href="{% url 'instagram_profile:followers_list' profile.user.username %}">Followers</a>:{{profile.get_count_of_followers}}</p>
<p><strong>Bio:</strong>{{profile.bio}}</p>
<img src="/media/{{profile.image_pic}}" width="400" height="400">
<h2>Posts:</h2>
{%for p in post %}
<a href="/post/{{profile.id}}/{{p.id}}"><img src="/media/{{p.first_image}}" width="200" height="200"></a>
{%endfor%}
<script>
  $('#subscribe-form').submit(function(e){
    e.preventDefault()
    var profile_id = $("#profile-id").val();
    var user_id = "{{request.user.id}}";
    if ($("#profile-id").attr('class')==='subscribe'){
      $.ajax({
        type:'post',
        url:"{% url 'api:add_subscriber' %}",
        data:{
          "profile_id":profile_id,
          "user_id":user_id,
          'csrfmiddlewaretoken': '{{ csrf_token }}'
        },
        dataType:'json',
        success:function(response){
          $("#profile-id").html("Unsubscribe").removeClass("subscribe").addClass("unsubscribe")
          $("#count-subscribers").html(response["subscriber_count"])
        },
        error:function(e,response){
          console.log(e,response.responseText)
        }
      })
    } else if ($("#profile-id").attr('class')==='unsubscribe'){
      $.ajax({
      type:'delete',
      url:"{% url 'api:delete_subscriber' profile_id=profile.id user_id=request.user.id%}",
      data:{
      },
      dataType:'json',
      success:function(response){
        $("#profile-id").html("Subscribe").removeClass("unsubscribe").addClass("subscribe")
        $("#count-subscribers").html(response["subscriber_count"])
      },
      error:function(e,response){
        console.log(e,response.responseText)
      }
    })
   }
  })

</script>
{% endblock %}

instagram/templates/instagram_profile/profile/profile_create.html
{%extends 'base.html' %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
  {%csrf_token%}
  {{form}}
</form>
<script>

{% endblock %}

instagram/templates/instagram_profile/profile/profile_list.html
{% extends 'base.html' %}
{% block content %}
<br>
{% for profile in profile_to_list %}
   <a href="{% url 'instagram_profile:profile' profile.id%}"><p><strong>{{profile.user.username}}<strong><p></a>
   <img src="/media/{{profile.image_pic}}" width="100" height="100">
   <hr>
{%endfor%}
{% endblock %}

instagram/templates/instagram_profile/profile/update_profile.html
{%extends 'base.html'%}
{%block content%}
{% if request.user.id == profile.id %}
   <form action="" method="POST" enctype="multipart/form-data">
     {%csrf_token%}
     {{username_form.as_p}}
     {{profile_form.as_p}}
     <button type="submit">Update</button>
   </form>
{%else%}
   <p>You are not allowed to see this page<p>
{%endif%}
{%endblock%}