instagram/api/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from api import views

app_name="api"

urlpatterns = [
  path("add_like/",views.CreateLikeView.as_view(),name="add_like"),
  path("image/<int:profile_id>/<int:post_id>/",views.ImageView.as_view(),name="image_view"),
  path("subscribe/",views.CreateSubscribeView.as_view(),name="add_subscriber"),
  path("comment/",views.CreateCommentView.as_view(),name="add_comment"),
  path("delete_subscribe/<profile_id>/<user_id>/",views.DeleteSubscribeView.as_view(),name="delete_subscriber"),
  path("delete_like/<post_id>/<user_id>/",csrf_exempt(views.DeleteLikeView.as_view()),name="delete_like")
]

instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("instagram_profile.urls",namespace="instagram_profile")),
    path("",include("accounts.urls",namespace="account")),
    path("",include("chat.urls",namespace="chat")),
    path("api/",include("api.urls",namespace="api"))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

instagram/instagram_profile/urls.py
from django.urls import path
from instagram_profile import views
# from instagram_profile.views import ProfileView


app_name="instagram_profile"
urlpatterns = [
   path("",views.index,name="index"),
   path("friends/",views.ProfileListView.as_view(),name="profile_list"),
   path("feed/",views.FeedView.as_view(),name="feed"),
   path("profile/<int:pk>/",views.ProfileView.as_view(),name="profile"),
   path("profile/update_profile/<int:pk>/",views.UpdateProfileView.as_view(),name="update_profile"),
   path("profile/subscribers/<str:username>/",views.SubscribersView.as_view(),name="subscribers_list"),
   path("profile/followers/<str:username>/",views.FollowersView.as_view(),name="followers_list"),
   path("post/<int:profile_id>/<int:post_id>/",views.PostView.as_view(),name="post"),
   path("post/add_post",views.AddPostView.as_view(),name="add_post"),
]

instagram/instagram_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from datetime import datetime
from django.urls import reverse

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    followers = models.ManyToManyField('Profile',related_name='profile_followers',blank=True)
    subscribers = models.ManyToManyField('Profile',related_name='profile_subscribers',blank=True)
    image_pic = ProcessedImageField(upload_to="photos",default="default.jpg",format='JPEG',options={'quality':100},null=True,blank=True)
    bio = models.CharField(max_length=200)
    created_at = models.DateTimeField(default=datetime.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=["created_at"]

    def get_count_of_post(self):
        return self.post_set.count()

    def get_count_of_subscribers(self):
        return self.subscribers.count()

    def get_count_of_followers(self):
        return self.followers.count()

    def __str__(self):
        return self.user.username



class Post(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now)
    text = models.CharField(max_length=200)
    first_image = ProcessedImageField(upload_to="first_image",format="JPEG",options={'quality':100},null=True,blank=True)

    def get_absolute_url(self):
        return reverse('post',args=[str(self.profile.id),str(self.id)])

    def get_count_of_likes(self):
        return self.like_set.count()

    def get_count_of_comments(self):
        return self.comment_set.count()

    def __str__(self):
        return "Post id:"+str(self.id)+" "+str(self.profile.user.username)


class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)

    class Meta:
        unique_together = ("post","user")

    def __str__(self):
        return "Id: "+str(self.id) + " Username:"+self.user.username+" Post:"+str(self.post.id)


class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    created_at = models.DateTimeField(default=datetime.now)

    def __str__(self):
            return "Id: "+str(self.id) + " Username:"+self.user.username+" Post:"+str(self.post.id)


class Image(models.Model):
    image_url = ProcessedImageField(upload_to="post",processors=[ResizeToFill(200,200)],format='JPEG',options={'quality':100},blank=True,null=True)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

instagram/instagram_profile/forms.py
from django import forms
from django.contrib.auth.models import User
from instagram_profile.models import Profile, Comment


class AddPostForm(forms.Form):
    text = forms.CharField(required=False)
    first_image = forms.ImageField()
    attachments = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple':True}),required=False)


class UpdateProfileForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super(UpdateProfileForm,self).__init__(*args,**kwargs)
        self.fields['bio'].required=False

    class Meta:
        model = Profile
        fields = ('image_pic','bio',)


class UsernameForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username',)

instagram/instagram_profile/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from instagram_profile.models import Profile,Image,Post, Comment, Like
from instagram_profile.forms import AddPostForm,UpdateProfileForm,UsernameForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
#for ajax,api
#HttpResponses,reverse
from django.http import HttpResponse
from django.urls import reverse
from django.http import HttpResponseRedirect
#Views
from django.views import View
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("instagram_profile:feed"))
    else:
        return HttpResponseRedirect(reverse("accounts:login"))


class UpdateProfileView(LoginRequiredMixin,UpdateView):
    model = Profile
    second_model = User
    form_class = UpdateProfileForm
    second_form_class = UsernameForm
    pk_url_kwarg = 'pk'
    template_name = "instagram_profile/profile/update_profile.html"

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return HttpResponseRedirect(reverse("instagram_profile:profile",args=(pk,)))

    def get_context_data(self,**kwargs):
        context = super(UpdateProfileView,self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        profile = get_object_or_404(self.model,id=int(pk))
        user = get_object_or_404(self.second_model,id=int(pk))
        context['profile_form'] = self.form_class(instance=profile)
        context['username_form'] = self.second_form_class(instance=user)
        return context

    def form_invalid(self,profile_form,username_form,*args,**kwargs):
        return self.render_to_response(self.get_context_data({'profile_form':profile_form,'username_form':username_form}))

    def post(self,request,*args,**kwargs):
        pk = self.kwargs.get('pk')
        profile = get_object_or_404(self.model,id=int(pk))
        user = get_object_or_404(self.second_model,id=int(pk))
        profile_form = self.form_class(instance=profile,data=request.POST,files=request.FILES)
        username_form = self.second_form_class(instance=user,data=request.POST)
        if profile_form.is_valid() and username_form.is_valid():
            profile_form.save()
            username_form.save()
            return self.get_success_url()
        else:
            return self.form_invalid(profile_form,username_form)


class AddPostView(View,LoginRequiredMixin):
    template_name = "instagram_profile/post/add_post.html"
    form_class = AddPostForm

    def get(self,request,*args,**kwargs):
        form = self.form_class()
        context = {"form":form}
        return render(request,self.template_name,context=context)

    def post(self,request,*args,**kwargs):
        profile = self.request.user.profile
        form = self.form_class(data=request.POST,files=request.FILES)
        if form.is_valid():
            text = form.cleaned_data["text"]
            first_image = form.cleaned_data["first_image"]
            attachments = self.request.FILES.getlist("attachments")
            post = Post(profile=profile,text=text,first_image=first_image)
            post.save()
            for im in attachments:
                Image.objects.create(post_id=post.id,image_url=im)
            return HttpResponseRedirect(reverse('instagram_profile:post',args=(profile.id,post.id)))


class PostView(DetailView):
    model = Post
    template_name = "instagram_profile/post/post.html"
    context_object_name = "post"

    def get_object(self,**kwargs):
        post_id = self.kwargs.get('post_id')
        return Post.objects.get(id=post_id)

    def get_context_data(self,**kwargs):
        context = super(PostView,self).get_context_data(**kwargs)
        post_id = self.kwargs.get('post_id')
        profile_id = self.kwargs.get('profile_id')
        comments = Comment.objects.filter(post__id=post_id,post__profile__id=profile_id)
        liked = False
        if Like.objects.filter(user=self.request.user.id,post__id=post_id).exists():
            liked = True
        context["is_liked"] = liked
        context["comments"] = comments
        return context


class ProfileView(View,LoginRequiredMixin):
    template_name = "instagram_profile/profile/profile.html"

    def get(self,request,*args,**kwargs):
        pk = self.kwargs.get('pk')
        profile = Profile.objects.get(id=pk)
        follower = request.user.profile
        post = Post.objects.filter(profile__id=pk)
        is_subscribed = True if follower in profile.subscribers.all() else False
        context = {"profile":profile,"post":post,"is_subscribed":is_subscribed}
        return render(request,self.template_name,context=context)


class SubscribersView(View,LoginRequiredMixin):
    template_name = "instagram_profile/subscribers/subscribers_list.html"

    def get(self,request,username):
        profile = Profile.objects.get(user=User.objects.get(username=username))
        subscribers = profile.subscribers.all()
        context={"subscribers":subscribers}
        return render(request,self.template_name,context=context)


class FollowersView(View,LoginRequiredMixin):
    template_name = "instagram_profile/followers/followers_list.html"

    def get(self,request,username):
        profile = Profile.objects.get(user=User.objects.get(username=username))
        followers = profile.followers.all()
        context = {"followers":followers}
        return render(request,self.template_name,context=context)


class ProfileListView(ListView,LoginRequiredMixin):
    model = Profile
    template_name = "instagram_profile/profile/profile_list.html"
    context_object_name = 'profile_to_list'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        return context


class FeedView(View,LoginRequiredMixin):
    template_name = "instagram_profile/feed/feed.html"

    def get(self,request):
        profile = Profile.objects.get(user=request.user.id)
        subscribers = profile.followers.all()
        posts = Post.objects.filter(profile__in=subscribers).order_by("created_at")
        context = {"posts":posts}
        return render(request,self.template_name,context=context)

instagram/templates/instagram_profile/post/add_post.html
{% extends 'base.html' %}
{%block content%}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Add post</button>
</form>
{%endblock%}

instagram/templates/instagram_profile/post/post.html
{%extends 'base.html'%}
{% load static %}
{% block content %}
<p><strong id="current"></strong>/<strong id="all"></strong></p>
<img src="/media/{{post.first_image}}" id="post-image" width="300" height="300">
<button id="prev">Prev</button>
<button id="next">Next</button>

<p>{{post.text}}</p>
<div id="like-section">
  <p>Like: <strong id="like-count">{{post.get_count_of_likes}}</strong></p>
  <form id="like-form">
    {%if is_liked%}
    <button type="submit" id="like" class="unlike_" name="post_id" value="{{post.id}}">Unlike</button>
    {%else%}
    <button type="submit" id="like" class="like_" name="post_id" value="{{post.id}}">Like</button>
  {%endif%}
  </form>
</div>

<h2>Comments</h2> <div id="count_comments">{{post.get_count_of_comments}}</div><hr>
<div id="my_comments">
  {% for comment in comments %}
  <p>
  <img src="/media/{{comment.user.profile.image_pic}}" width="50" height="50"></img>
  <strong>{{comment.user.username}}</strong> {{comment.text}}
  </p>
  {%endfor%}
</div>
  <form id="form-comments">
    {%csrf_token%}
    <textarea cols="60" rows="7" id="id_comment_text"></textarea>
    <input type='hidden' id='post_id' name='post' value='{{post.id}}'>
    <input type="submit" value="Add comment">
  </form>
<script>
$(document).ready(function(){
  $('#like-form').submit(function(e){
    event.preventDefault();
    var pk = $('#like').val();
    var user = String({{request.user.id}});
    if ($("#like").attr('class')==="like_"){
      $.ajax({
        type:'post',
        url:"{%url 'api:add_like' %}",
        data:{
          'post':pk,
          'user':user,
          'csrfmiddlewaretoken': '{{ csrf_token }}'
        },
        dataType:'json',
        success:function(response) {
          $("#like").html("Unlike").removeClass("like_").addClass("unlike_")
          $("#like-count").html(response["total_likes"])
        },
        error:function(response,e){
          console.log(response.responseText)
        }
      })
    } else {
      $.ajax({
        type:'delete',
        url: `{%url 'api:delete_like' post_id=post.id user_id=user.id%}`,
        data:{},
        dataType:'json',
        success:function(response) {
          $("#like").html("Like").removeClass("unlike_").addClass("like_")
          $("#like-count").html(response["total_likes"])
        },
        error:function(response,e){
          console.log(response.responseText)
        }
      })
    }

  })
})
</script>
<script type="text/javascript">window.CSRF_TOKEN = "{{ csrf_token }}";</script>
<script>
$(document).ready(function(){
  $("#form-comments").submit(function(e) {
    e.preventDefault();
    var comment_text = $("#id_comment_text").val();
    var user = String({{request.user.id}});
    var post_id = $("#post_id").val();

    $.ajax({
      type:'POST',
      url:"{%url 'api:add_comment' %}",
      data:{
        "text":comment_text,
        "user":user,
        "post":post_id,
        csrfmiddlewaretoken: '{{ csrf_token }}'
      },
      success: function(response) {
        $('#form-comments').trigger('reset');
        $("#comment_text").focus();
        $("#my_comments").append(
          `<p>
            <img src="${response["image_pic"]}" width="50" height="50"></img>
            <strong>${response["username"]}</strong> ${response["comment_text"]}
          </p>`
          )
        }
    })
  })
})
</script>
<script>
let counter = -1;
let current=1
fetch("{% url 'api:image_view' post.profile.id post.id%}")
  .then((response) => {
    return response.json();
  })
  .then((data)=>{

      document.getElementById("all").innerHTML=data.length+1
      document.getElementById("current").innerHTML=current;
      document.getElementById('next').addEventListener('click',function() {
        if (counter===data.length-1) {
          counter=data.length-1
          if (current===data.length+1) {
            current=data.length+1
            document.getElementById("current").innerHTML=current
          } else {
            document.getElementById("current").innerHTML=current
            current++
          }
        }  else {
          counter++
          current++
          document.getElementById("current").innerHTML=current
          document.getElementById('post-image').setAttribute('src',data[counter].image_url)
        }
      })
      document.getElementById('prev').addEventListener('click',function() {
        if (counter===0) {
          counter=-1
          document.getElementById('post-image').setAttribute('src',"/media/{{post.first_image}}")
          if (current===2) {
            current=1
            document.getElementById("current").innerHTML=current
          }
        } else if (counter!=-1){
          counter--
          current--
          document.getElementById("current").innerHTML=current
          document.getElementById('post-image').setAttribute('src',data[counter].image_url)
        }
      })
  })

</script>
{% endblock %}